### ISSUE TITLE
The `schedule` subcommands

### ISSUE THREAD

**Issue by dbosk** [dbosk/nytid#16]
The `schedule` command should list the user's schedule.

- [ ] First, by outputting tab-separated CSV (#14) by default.
- [x] But also by option to output to ICS format (#11).
- [x] For this we need the `config` command to set URLs to schedules, #15 .
- [x] Add `time` subcommand that summarizes total teaching time for all scheduled teaching.
   - [ ] Add options for different values.
   - [ ] Add interactive mode to set values for each event.
   - [ ] Store result in data directory.
   - [x] Option to write signup sheet to local file (not in data directory).
- [x] `show` command shows own events and who else signed up.
   - [x] Add option `--all` to include all events. (`--user ""` has this effect.)
- [x] Add `ics` command that does the same as `show` but outputs ICS data.

**Comment by dbosk** [comment]
We've done the most relevant points.
